[tool.isort]
profile = "black"
multi_line_output = 3

[tool.ruff]
lint.select = [
    "INP001",   # implicit-namespace-package
    "C9",       # Complexity, McCabe
    "C",        # pylint conventions
    "F",        # Fixable errors, Pyflakes
    "E",        # Errors, pycodestyle
    "W",        # Warning, pycodestyle
    "I",        # isort
    "N",        # pep8-naming
    "COM",      # flake8-commas
    "B",        # flake8-bugbear
    "T",        # flake8-bandit
    "S",        # flake8-string-format
    "Q",        # flake8-quotes
    "TID",      # flake8-tidy-imports
    "TCH",      # flake8-type-checking
    "RUF",      # ruff specific rules
    "ANN",      # flake80-annotations
]
lint.ignore = [
    "ERA001",   # Found commented-out code
    "RET504",   # Unnecessary assignment to `input_str` before `return` statement
    "TRY003",   # Avoid specifying long messages outside the exception class
    "C901",     # `query_workspace_open_search` is too complex (28 > 10)
#    "TID252",   # Prefer absolute imports over relative imports from parent modules
]
include = [
    "pyproject.toml",
    "./core/",
    "./database/**/*.py",
    "./endpoints/**/*.py",
    "./schemas/**/*.py",
    "./services/**/*.py",
    "./dependencies.py",
    "./main.py",
]

# black compatibility
line-length = 120

[tool.ruff.format]
quote-style = "double"
